apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: go-microservice
    spec:
      containers:
      - name: microservice
        image: stevesloka/microservice-sample:0.0.1
        env:
          - name: SERVICE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: admin
          containerPort: 8080
          protocol: TCP
