apiVersion: v1
kind: Service
metadata:
  name: go-microservice
spec:
  type: NodePort
  ports:
  - name: go-microservice
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: go-microservice